export const images = {
    Sunny: "/src/assets/Sunny.jpg",
    Cloudy: "/src/assets/clouds.jpg",
    "Partly Cloudy": "/src/assets/Partly_cloudy.jpg",
    "Partly cloudy": "/src/assets/Partly_cloudy.jpg",
    "overcast clouds": "/src/assets/Partly_cloudy.jpg",
    "few clouds":"/src/assets/clouds.jpg",
    Mist: "/src/assets/Mist.jpg",
    mist : "/src/assets/Mist.jpg",
    Rain: "/src/assets/Rain.jpg",
    Snow: "/src/assets/Rain.jpg",
    Thunderstorm: "/src/assets/Thunderstorm.jpg",
    "Patch rain nearby": "/src/assets/Patchy_rain_nearby.jpg",
    "Light rain": "/src/assets/Patchy_rain_nearby.jpg",
    Fog: "/src/assets/fog.jpg",
    Clear: "/src/assets/Clear.jpeg",
    "clear sky": "/src/assets/Clear.jpeg",
    "Moderate rain": "/src/assets/Patchy_rain_nearby.jpg",
  };
